[package]
name = "rag"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = { version = "1.15", features = ["uuid"] }
serde_json = "1.0.151"
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["v4", "serde"] }

[dev-dependencies]
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
