apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://{{ include "legoos.componentName" (dict "root" $ "component" "prometheus") }}:{{ .Values.prometheus.service.port }}
    isDefault: true
